import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../Utils/requests';

export default function Home({ results }) {

  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Nav />
        <Results results={results} />
      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const res = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await res.json();
  return {
    props: {
      results: data
    }
  }
}
